name: project

topology:
  defaults:
    kind: linux
    image: praqma/network-multitool:latest
  nodes:
    router1:
      kind: linux
      image: frrouting/frr:v7.5.1
      binds:
        - router1/daemons:/etc/frr/daemons
        - router1/frr.conf:/etc/frr/frr.conf
    router2:
      kind: linux
      image: frrouting/frr:v7.5.1
      binds:
        - router2/daemons:/etc/frr/daemons
        - router2/frr.conf:/etc/frr/frr.conf
    router3:
      kind: linux
      image: frrouting/frr:v7.5.1
      binds:
        - router3/daemons:/etc/frr/daemons
        - router3/frr.conf:/etc/frr/frr.conf

    router4:
      kind: linux
      image: frrouting/frr:v7.5.1
      binds:
        - router4/daemons:/etc/frr/daemons
        - router4/frr.conf:/etc/frr/frr.conf

    PC1:
      exec:
        - ip addr add 192.168.4.2/24 dev eth1
        - ip route replace 0/0 via 192.168.4.1
      
    PC2:
      exec:
        - ip addr add 192.168.5.2/24 dev eth1
        - ip route replace 0/0 via 192.168.5.1
      
    PC3:
      exec:
        - ip addr add 192.168.6.2/24 dev eth1
        - ip route replace 0/0 via 192.168.6.1
      

  links:
    - endpoints: ["router1:eth1", "router4:eth1"]
    - endpoints: ["router1:eth3", "router2:eth3"]
    - endpoints: ["router2:eth1", "router4:eth2"]
    - endpoints: ["router3:eth1", "router4:eth3"]
    - endpoints: ["PC1:eth1", "router1:eth2"]
    - endpoints: ["PC2:eth1", "router2:eth2"]
    - endpoints: ["PC3:eth1", "router3:eth2"]